### ISSUE TITLE
CORS error on flutter web when sending events

### ISSUE THREAD

**Issue by johannesstricker** [aptabase/aptabase_flutter#21]
Hey, I wanted to try aptabase for flutter web, but events cannot be sent to the server due to CORS issues. 

```
Access to XMLHttpRequest at 'https://eu.aptabase.com/api/v0/events' from origin 'http://localhost:5001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

As you can see, I'm running locally on port 5001. I tested this against self-hosted and managed aptabase and got the same problem with both. Is this a known issue? I thought that aptabase accepts any origins by default.

**Comment by adrian-moisa** [comment]
I have the same issue. Any advice?

**Comment by adrian-moisa** [comment]
@johannesstricker have you found a fix? Cheers!

**Comment by adrian-moisa** [comment]
@cristipufu  I have the same issue. Any advice?

**Comment by cristipufu** [comment]
It looks like it allows any origin (but the requests need the `content-type` and `app-key` headers:
https://github.com/aptabase/aptabase/blob/main/src/Program.cs#L59
```C#
            options.AddPolicy(name: "AllowAny", policy =>
            {
                policy.AllowAnyOrigin()
                    .WithHeaders("content-type", "app-key")
                    .WithMethods("POST")
                    .SetPreflightMaxAge(TimeSpan.FromHours(1));
            });
```

**Comment by adrian-moisa** [comment]
@cristipufu I suppose all we need is a commit which adds `"content-type", "app-key"` at: 

https://github.com/aptabase/aptabase_flutter/blob/7abd7350cd7dc13cf083f6d1f724a34fdfc89c9e/lib/aptabase_flutter.dart#L228
```sh
      if (!kIsWeb) {
        request.headers.set(HttpHeaders.userAgentHeader, _sdkVersion);
      }
```

**Comment by cristipufu** [comment]
the sdk looks good:
```
final request = await _http.postUrl(apiUrl);

      request.followRedirects = true;
      request.headers
        ..set("App-Key", _appKey)
        ..set(
          HttpHeaders.contentTypeHeader,
          "application/json; charset=UTF-8",
        );
```

it's a POST and adds both those http headers.

**Comment by Deishelon** [comment]
Saw the same issue, should the back-end allow `OPTIONS` too?

![Image](https://github.com/user-attachments/assets/2f7b0c33-8786-47ea-b464-f4a76fc23b18)

**Comment by cristipufu** [comment]
@Deishelon nice catch man, this should fix the issue: https://github.com/aptabase/aptabase/commit/b8ad2432ca7c2ccb01fdb34f421be12daffd71a7

**Comment by Deishelon** [comment]
> @Deishelon nice catch man, this should fix the issue: https://github.com/aptabase/aptabase/commit/b8ad2432ca7c2ccb01fdb34f421be12daffd71a7

Let me know when the fix is deployed, I can give it a test :)

**Comment by Deishelon** [comment]
Hmm, still the same, I did notice the headers show this as well
```
server: BunnyCDN-AUC1-1213
cdn-proxyver: 1.19

```
Any proxies that are in front of the real backend that may need config update too ?

**Comment by cristipufu** [comment]
Yeah, we need to exclude this API from bunny cdn

**Comment by cristipufu** [comment]
@Deishelon can you please check again?

**Comment by Deishelon** [comment]
Yup, works now

![Image](https://github.com/user-attachments/assets/82ef8b4b-4aa9-4dc4-a478-53bf11fad11a)

Thanks for the quick fix!
